db:
  host:
  port: 3306
  username:
  password:
  database:
  synchronize: true
jwt:
  staticKey: false
  privateKeyPath: fileStorage/keys/privateKey.pem
  publicKeyPath: fileStorage/keys/publicKey.pem
server:
  enableAuthorization: true
  initialAdmin:
    username: admin
    password: Test@123
